/* eslint-env node, es2021 */
/* global BigInt */

const express = require("express");
const router = express.Router();
const { Connection, PublicKey } = require("@solana/web3.js");
const { getAssociatedTokenAddress } = require("@solana/spl-token");

const User = require("../model/User");
const DrawIntent = require("../model/DrawIntent");

/** ─ CONFIG ─ */
const RPC_URL = process.env.SOLANA_RPC || "https://api.mainnet-beta.solana.com";
const TREASURY_PUBKEY = new PublicKey(
  process.env.TREASURY_PUBKEY || "8yUGx6tMGsCxSdVj2Fk8FyaDkg4doZ32xnkNkzKSwHe5"
);
const SD_TOKEN_MINT = new PublicKey(
  process.env.SD_TOKEN_MINT || "3WBoV8iTFfa6fjsc66NLKyZJDftSSpbtJ1r6fjJfpump"
);
// price in whole SD tokens (e.g. 20)
const DRAW_PRICE_SD = parseInt(process.env.DRAW_PRICE_SD || "10", 10);

const TOKEN_PROGRAM_ID = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
const TOKEN_2022_PROGRAM_ID = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
const MEMO_PROGRAM_ID = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr";

/** ─ CARD META ─
 *  Full card pool (1..N) with badge-derived power, generated by scripts/matchBadges.js.
 *  { "<id>": { name, power, rarity } }
 */
const CARD_METADATA = require("../util/cardMetadata.json");
const ALL_CARD_IDS = Object.keys(CARD_METADATA);

/** ─ UTILS ─
 *  3-tier rarity from badge-derived power (matches the client styling + inventory route)
 */
const tierOf = (power) =>
  power >= 10 ? "Legendary" : power >= 8 ? "Rare" : "Common";
const rarityOf = (id) =>
  tierOf(Number(CARD_METADATA[String(id)]?.power) || 1);

// Pre-bucket every card by rarity tier so draws can be weighted across the whole pool.
const DRAW_BUCKETS = { Common: [], Rare: [], Legendary: [] };
for (const id of ALL_CARD_IDS) {
  DRAW_BUCKETS[tierOf(Number(CARD_METADATA[id].power) || 1)].push(id);
}
// draw weights (sum 100): rarer tiers far less likely
const DRAW_WEIGHTS = [
  ["Legendary", 10],
  ["Rare", 20],
  ["Common", 70],
];
/** pick a random cardId weighted by rarity tier (falls back to any id) */
function pickCardId() {
  const roll = Math.random() * 100;
  let acc = 0;
  for (const [tier, w] of DRAW_WEIGHTS) {
    acc += w;
    const arr = DRAW_BUCKETS[tier];
    if (roll < acc && arr && arr.length) {
      return arr[Math.floor(Math.random() * arr.length)];
    }
  }
  return ALL_CARD_IDS[Math.floor(Math.random() * ALL_CARD_IDS.length)];
}

function priceToBaseUnits(priceSD, decimals) {
  // 6dp fixed → BigInt
  let base = BigInt(Math.round(Number(priceSD) * 1_000_000));
  if (decimals >= 6) base *= BigInt(10) ** BigInt(decimals - 6);
  else base /= BigInt(10) ** BigInt(6 - decimals);
  return base;
}

/** Robust verifier:
 *  - Ensures memo matches the intent
 *  - Finds a transferChecked for the SD mint with the expected amount
 *  - Verifies source token account is owned by buyer
 *  - Verifies destination token account is owned by treasury
 *  Accepts *any* SPL token accounts (ATA or non-ATA) as long as owners match.
 */
async function verifyDrawPayment({
  connection,
  txSignature,
  buyerWallet,
  memo,
}) {
  const tx = await connection.getParsedTransaction(txSignature, {
    maxSupportedTransactionVersion: 0,
    commitment: "confirmed",
  });
  if (!tx) return { ok: false, reason: "Transaction not found" };

  // 1) memo check
  let memoOk = false;
  for (const ix of tx.transaction.message.instructions || []) {
    const program =
      ix.programId?.toBase58?.() || ix.program || ix.programId?.toString?.();
    if (program === MEMO_PROGRAM_ID || ix.program === "spl-memo") {
      if (typeof ix.parsed === "string" && ix.parsed === memo) {
        memoOk = true;
        break;
      }
      if (ix.data) {
        try {
          const buf = Buffer.from(ix.data, "base64");
          if (buf.toString("utf8") === memo) {
            memoOk = true;
            break;
          }
        } catch {}
      }
    }
  }
  if (!memoOk) return { ok: false, reason: "Missing memo" };

  // 2) expected amount (decimals from postTokenBalances; fallback 6)
  const decimals =
    tx.meta?.postTokenBalances?.find((b) => b.mint === SD_TOKEN_MINT.toString())
      ?.uiTokenAmount?.decimals ?? 6;
  const expected = priceToBaseUnits(DRAW_PRICE_SD, decimals);

  // 3) locate a matching transferChecked and verify account owners
  const ixs = tx.transaction.message.instructions || [];
  for (const ix of ixs) {
    const p = ix?.parsed;
    const programId = ix.programId?.toString?.() || ix.program;
    if (!p) continue;
    const isTokenProg =
      ix.program === "spl-token" || ix.program === "spl-token-2022" ||
      programId === TOKEN_PROGRAM_ID || programId === TOKEN_2022_PROGRAM_ID;
    if (!isTokenProg) continue;
    if (p.type !== "transferChecked") continue;

    const mint = p.info?.mint;
    const amount = BigInt(p.info?.tokenAmount?.amount || "0");
    const src = p.info?.source;
    const dst = p.info?.destination;

    if (mint !== SD_TOKEN_MINT.toString()) continue;
    if (amount !== expected) continue;

    // Verify src owner == buyer & dst owner == treasury
    const [srcInfo, dstInfo] = await Promise.all([
      connection.getParsedAccountInfo(new PublicKey(src)),
      connection.getParsedAccountInfo(new PublicKey(dst)),
    ]);

    const srcOwner =
      srcInfo?.value?.data?.parsed?.info?.owner ||
      srcInfo?.value?.data?.parsed?.info?.owner?.toString?.();
    const srcMint = srcInfo?.value?.data?.parsed?.info?.mint;
    const dstOwner =
      dstInfo?.value?.data?.parsed?.info?.owner ||
      dstInfo?.value?.data?.parsed?.info?.owner?.toString?.();
    const dstMint = dstInfo?.value?.data?.parsed?.info?.mint;

    const srcOwnerOk = srcOwner === buyerWallet;
    const dstOwnerOk = dstOwner === TREASURY_PUBKEY.toBase58();
    const srcMintOk = srcMint === SD_TOKEN_MINT.toBase58();
    const dstMintOk = dstMint === SD_TOKEN_MINT.toBase58();

    if (srcOwnerOk && dstOwnerOk && srcMintOk && dstMintOk) {
      return { ok: true };
    }
  }

  return { ok: false, reason: "Token transfer mismatch" };
}

/** ─ ROUTES ─
 *  /api/draw-card/intent
 *  /api/draw-card/finalize
 *  /api/draw-card/pending
 *  /api/draw-card/cancel
 *  /api/draw-card/free
 */

/** POST /api/draw-card/intent  { walletAddress } */
router.post("/intent", async (req, res) => {
  const { walletAddress } = req.body;
  if (!walletAddress)
    return res.status(400).json({ error: "Missing walletAddress" });

  const user = await User.findOne({ walletAddress });
  if (!user) return res.status(404).json({ error: "User not found" });

  // If free draw available, no intent needed
  if (user.newPlayer && user.freeCard > 0) {
    return res.json({ free: true });
  }

  // Create a unique memo for this intent
  const memo = `DRAW:${walletAddress}:${Date.now().toString(36)}:${Math.random()
    .toString(36)
    .slice(2, 10)}`;

  const doc = await DrawIntent.create({
    wallet: walletAddress,
    memo,
    priceSD: DRAW_PRICE_SD,
    status: "locked",
    lockedAt: new Date(),
  });

  res.json({
    free: false,
    memo: doc.memo,
    priceSD: DRAW_PRICE_SD,
    mint: SD_TOKEN_MINT.toBase58(),
    treasury: TREASURY_PUBKEY.toBase58(),
  });
});

/** GET /api/draw-card/pending?wallet=<addr> */
router.get("/pending", async (req, res) => {
  const wallet = req.query.wallet || "";
  const rows = await DrawIntent.find({
    wallet,
    status: "locked",
  })
    .sort({ lockedAt: -1 })
    .select("memo priceSD lockedAt")
    .lean();

  res.json({ pending: rows });
});

/** POST /api/draw-card/cancel  { walletAddress, memo } */
router.post("/cancel", async (req, res) => {
  const { walletAddress, memo } = req.body;
  if (!walletAddress || !memo) {
    return res.status(400).json({ error: "Missing fields" });
  }

  const doc = await DrawIntent.findOne({
    wallet: walletAddress,
    memo,
    status: "locked",
  });
  if (!doc) {
    return res
      .status(404)
      .json({ error: "No locked intent found for this wallet & memo" });
  }

  doc.status = "expired";
  await doc.save();
  res.json({ ok: true });
});

/** POST /api/draw-card/finalize  { walletAddress, txSignature, memo } */
router.post("/finalize", async (req, res) => {
  const { walletAddress, txSignature, memo } = req.body;
  if (!walletAddress || !txSignature || !memo) {
    return res.status(400).json({ error: "Missing fields" });
  }

  const intent = await DrawIntent.findOne({
    wallet: walletAddress,
    memo,
    status: "locked",
  });
  if (!intent)
    return res
      .status(409)
      .json({ error: "Intent not found or already finalized" });

  const connection = new Connection(RPC_URL, "confirmed");

  // Verify payment (robust)
  const verified = await verifyDrawPayment({
    connection,
    txSignature,
    buyerWallet: walletAddress,
    memo,
  });
  if (!verified.ok) {
    // surface exact reason to the client
    return res.status(403).json({ error: verified.reason || "Verify failed" });
  }

  // Award the card
  const user = await User.findOne({ walletAddress });
  if (!user) return res.status(404).json({ error: "User not found" });

  // rarity-weighted draw across the full card pool
  const idStr = String(pickCardId());
  const meta = CARD_METADATA[idStr];
  if (!meta) return res.status(500).json({ error: "Card metadata missing" });

  const existing = user.cards.find(
    (c) => c.cardId === idStr && c.isFree === false
  );
  if (existing) existing.count += 1;
  else
    user.cards.push({
      cardId: idStr,
      name: meta.name,
      power: meta.power,
      count: 1,
      isFree: false,
    });

  await user.save();

  // Close the intent idempotently
  intent.status = "completed";
  intent.txSignature = txSignature;
  await intent.save();

  res.json({
    drawnCard: idStr,
    name: meta.name,
    power: meta.power,
    rarity: rarityOf(idStr),
    updatedUser: user,
  });
});

/** FREE draw (unchanged) */
router.post("/free", async (req, res) => {
  const { walletAddress } = req.body;
  if (!walletAddress)
    return res.status(400).json({ error: "Missing walletAddress" });

  const user = await User.findOne({ walletAddress });
  if (!user) return res.status(404).json({ error: "User not found" });

  if (!(user.newPlayer && user.freeCard > 0)) {
    return res.status(403).json({ error: "No free draw available" });
  }

  user.freeCard -= 1;
  if (user.freeCard === 0) user.newPlayer = false;

  // rarity-weighted draw across the full card pool
  const idStr = String(pickCardId());
  const meta = CARD_METADATA[idStr];
  if (!meta) return res.status(500).json({ error: "Card metadata missing" });

  const existing = user.cards.find(
    (c) => c.cardId === idStr && c.isFree === true
  );
  if (existing) existing.count += 1;
  else
    user.cards.push({
      cardId: idStr,
      name: meta.name,
      power: meta.power,
      count: 1,
      isFree: true,
    });

  await user.save();

  res.json({
    drawnCard: idStr,
    name: meta.name,
    power: meta.power,
    rarity: rarityOf(idStr),
    updatedUser: user,
  });
});

module.exports = router;
