// NFT card art for the full 5000-card pool.
// Thumbnails are served statically from public/cards5k/<id>.webp
// (generated by scripts/makeThumbs.js from src/components/assets/images/webp.5k.nfts).
const PUB = process.env.PUBLIC_URL || "";

export const nftArt = (cardId) => {
  if (cardId == null) return null;
  const m = String(cardId).match(/\d+/);
  return m ? `${PUB}/cards5k/${m[0]}.webp` : null;
};

export default nftArt;
